apiVersion: v1
kind: ServiceAccount
metadata:
  name: volume-snapshot-editor
  namespace: monitoring
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.roleArn }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: apigee
  name: volume-snapshot-editor
rules:
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots", "volumesnapshotcontent"]
  verbs: ["get", "list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: volume-snapshot-editor
  namespace: apigee
subjects:
- kind: ServiceAccount
  name: volume-snapshot-editor
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: volume-snapshot-editor
  apiGroup: rbac.authorization.k8s.io
